# Generated by Django 3.0 on 2019-12-23 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_auto_20191223_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(db_column='cart', on_delete=django.db.models.deletion.CASCADE, to='payment.UserProfile'),
        ),
    ]
