# Generated by Django 3.0 on 2019-12-24 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_auto_20191224_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.AddField(
            model_name='cart',
            name='userprofile',
            field=models.ForeignKey(db_column='cart_it', default=9, on_delete=django.db.models.deletion.CASCADE, to='payment.UserProfile'),
            preserve_default=False,
        ),
    ]
