# Generated by Django 3.0 on 2019-12-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_auto_20191224_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',  
            name='category',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
