# Generated by Django 3.0 on 2020-01-02 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_productmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='catid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PrevOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('userprofile', models.ForeignKey(db_column='prevorder_it', on_delete=django.db.models.deletion.CASCADE, to='payment.UserProfile')),
            ],
        ),
    ]
