# Generated by Django 3.0 on 2020-01-02 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0015_auto_20200102_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrevOrder2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('userprofile', models.ForeignKey(db_column='prevorder_it', on_delete=django.db.models.deletion.CASCADE, to='payment.UserProfile')),
            ],
        ),
    ]
