# Generated by Django 3.0 on 2020-01-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0016_prevorder2'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='peakhour',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
