# Generated by Django 3.0 on 2020-01-02 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0017_userprofile_peakhour'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrevOrder2',
        ),
    ]
