# Generated by Django 3.0 on 2020-01-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0020_auto_20200102_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hot_hour',
            field=models.IntegerField(null=True),
        ),
    ]
