# Generated by Django 3.0 on 2020-01-06 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0024_auto_20200106_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='secretid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(max_length=10)),
                ('userprofile', models.ForeignKey(db_column='s_no', on_delete=django.db.models.deletion.CASCADE, to='payment.UserProfile')),
            ],
        ),
        migrations.DeleteModel(
            name='dummy',
        ),
    ]
