# Generated by Django 3.0 on 2020-01-09 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0025_auto_20200106_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pro-imgs/'),
        ),
    ]
